[package]
name = "folding-schemes"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.4.2"
ark-ff = "^0.4.0"
ark-poly = "^0.4.0"
ark-std = "^0.4.0"
ark-crypto-primitives = { version = "^0.4.0", default-features = false, features = ["r1cs", "sponge"] }
ark-relations = { version = "^0.4.0", default-features = false }
ark-r1cs-std = { version = "^0.4.0", default-features = false }
rayon = "1.7.0"
byteorder = "=1.4.3"
ark-bn254 = { version = "=0.4.0" }
hex = "=0.4.3"

# tmp imports for espresso's sumcheck
ark-serialize = "0.4.2"
espresso_subroutines = {git="https://github.com/EspressoSystems/hyperplonk", package="subroutines"}
espresso_transcript = {git="https://github.com/EspressoSystems/hyperplonk", package="transcript"}

# wasm operations for Circom's witness calculation
wasmer = { version = "=2.3.0", default-features = false }
fnv = { version = "=1.0.7", default-features = false }
num = { version = "=0.4.0" }
num-traits = { version = "=0.2.15", default-features = false }
num-bigint = { version = "=0.4.3", default-features = false, features = ["rand"] }

# error handling
color-eyre = "=0.6.2"
criterion = "=0.3.6"
cfg-if = "=1.0.0"
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
ark-pallas = {version="0.4.0", features=["r1cs"]}
ark-vesta = {version="0.4.0"}
ark-crypto-primitives = { version = "^0.4.0", default-features = false, features = ["crh"] }
serde_json = "=1.0.94"

[features]
default = ["parallel", "nova", "hypernova", "wasmer/default", "circom-2"]
hypernova=[]
nova=[]
wasm = ["wasmer/js-default"]
circom-2 = []

parallel = [ 
    "ark-std/parallel", 
    "ark-ff/parallel",  
    "ark-poly/parallel", 
    ]
